### ISSUE TITLE
HU13 - Crear premios

### ISSUE THREAD

**Issue by je-guerreroa1-uniandes** [je-guerreroa1-uniandes/grupo-12-software-mobile#1]
Como coleccionista quiero crear nuevos premios para poder asociarlos a los artistas.

_Criterio de aceptación:_

- El campo de nombre del premio no debe estar vacío.
- El campo de descripción del premio no debe estar vacío.
- El campo del nombre del artista al que se le va asociar el premio no debe estar vacío.
- Debe haber un botón de crear.

_Sub tareas:_

- [ ] Modelar la respuestas con TDD - Mocks | 2h
- [ ] Integración servicio (Pruebas integración) | 2h
- [ ] Implementación UI | 1h 30m
- [ ] Integración UI + Servicio | 1h 30m
- [ ] Pruebas espresso | 1h
- [ ] Code review | 20m

_Mockup(UI)_

![Image](https://user-images.githubusercontent.com/111321588/232256017-6f935941-c0aa-47d9-b7b4-014e774d58a4.png)

**Comment by Paolaafb22** [comment]
<html>
<body>


Criterio | Comentario | 
-- | -- |
Completo |  La historia es objetiva en su enunciación y se observa en el mockup es consistente con lo solicitado sin embargo no es claro cuál es el campo para signar el artista con el premio| 
Consistente | ✔️ la historias de usuario es coherente con la necesidad planteada por el usuario|
Negociable | ✔️ La historia es negociable porque se presenta como necesaria | 
Valiosa | ✔️ La historia genera valor a la solución del problema mostrado por el usuario coleccionista | 
Estimable | ✔️  La historia es estimable ya que esta detallada y delimitada la funcionalidad a crear de acuerdo a sus criterios | 
Pequeña | ✔️ La historia está delimitada y muestra el objetivo de consultar catálogo de álbumes . | 
Comprobable | ✔️ La historia se puede comprobar al replicar los pasos y los criterios de aceptación. |
