### ISSUE TITLE
HU14 - Agregar un premio a un artista

### ISSUE THREAD

**Issue by je-guerreroa1-uniandes** [je-guerreroa1-uniandes/grupo-12-software-mobile#3]
Como coleccionista quiero agregar un premio a un artista para actualizar su información.

*Criterio de aceptación:*

* Se debe poder modificar la información de un artista existente.
* En caso de algún error al agregar un premio, se debe mantener la selección para reintentar.
* Si cancela la operación, debe volver a la pantalla anterior sin agregar el premio al artista.

*Sub tareas:*

- [ ] Modelar la respuestas con TDD - Mocks | 2h
- [ ] Integración servicio (Pruebas integración) | 2h
- [ ] Implementación UI | 1h 30m
- [ ] Integración UI + Servicio | 1h 30m
- [ ] Pruebas espresso | 1h
- [ ] Code review | 20m
- [ ] Merge conflicts(Opcional)

*Mockup(UI)*

![Image](https://user-images.githubusercontent.com/98400664/232345790-b1f3bf2a-6cb0-489a-b280-7bc286c8a603.png)

**Comment by BaezRincon** [comment]
<html>
<body>


Criterio | Comentario | 
-- | -- |
Completo | ✔️ La historia esta completa porque contiene lo necesario para cumplir con su objetivo. | 
Consistente | ✔️ La historia es consistente porque no presenta contradicciones ni inconsistencias |
Negociable | ✔️ La historia es negociable porque se presenta como necesaria | 
Valiosa | ✔️ La historia genera valor al cliente porque cubre un requerimiento necesario | 
Estimable | ✔️ La historia se puede estimar porque se puede estimar el esfuerzo para desarrollar la historia en una tecnología definida y conocida. | 
Pequeña | ✔️ La historia tiene un tamaño pequeño puede ser desarrollada en menos de 3 o 4 días para equipos de desarrollo de dos personas. | 
Comprobable | ✔️ La historia es comprobable porque la descripción de la historia y de los criterios de aceptación son suficientes para comprobar la correcta ejecución de la historia. |
