### ISSUE TITLE
HU11 - Agregar álbum a coleccionista

### ISSUE THREAD

**Issue by BaezRincon** [je-guerreroa1-uniandes/grupo-12-software-mobile#5]
Como coleccionista quiero agregar un álbum para poder venderlo o intercambiarlo

_Criterio de aceptación:_

- El campo de nombre del álbum no debe estar vacío.
- El campo de Cover URL del álbum no debe estar vacío.
- El campo de Release date del álbum no debe estar vacío.
- El campo de genre del álbum no debe estar vacío.
- El campo de record label del álbum no debe estar vacío.
- Debe haber un botón de crear.

_Sub tareas:_

- [ ] Modelar la respuestas con TDD - Mocks | 2h
- [ ] Integración servicio (Pruebas integración) | 2h

- [ ] Implementación UI | 1h 30m
- [ ] Integración UI + Servicio | 1h 30m
- [ ] Pruebas espresso | 1h
- [ ] Code review | 20m
- [ ] Merge conflicts(Opcional)

_Mockup(UI)_

![Image](https://user-images.githubusercontent.com/98714523/232353328-fd202d62-0937-4a16-94f7-51f6211058d2.png)

**Comment by BaezRincon** [comment]
<html>
<body>


Criterio | Comentario | 
-- | -- |
Completo | ✔️ La historia esta completa porque contiene lo necesario para cumplir con su objetivo. | 
Consistente | ✔️ La historia es consistente porque no presenta contradicciones ni inconsistencias |
Negociable | ✔️ La historia es negociable porque se presenta como necesaria | 
Valiosa | ✔️ La historia genera valor al cliente porque cubre un requerimiento necesario | 
Estimable | ✔️ La historia se puede estimar porque se puede estimar el esfuerzo para desarrollar la historia en una tecnología definida y conocida. | 
Pequeña | ✔️ La historia tiene un tamaño pequeño puede ser desarrollada en menos de 3 o 4 días para equipos de desarrollo de dos personas. | 
Comprobable | ✔️ La historia es comprobable porque la descripción de la historia y de los criterios de aceptación son suficientes para comprobar la correcta ejecución de la historia. |

**Comment by je-guerreroa1-uniandes** [comment]
Objeto coleccionista:
{
    "id": 100,
    "name": "Manolo Bellon",
    "telephone": "3502457896",
    "email": "manollo@caracol.com.co",
    "comments": [
        {
            "id": 100,
            "description": "The most relevant album of Ruben Blades",
            "rating": 5
        }
    ],
    "favoritePerformers": [
        {
            "id": 100,
            "name": "Rubén Blades Bellido de Luna",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Ruben_Blades_by_Gage_Skidmore.jpg/800px-Ruben_Blades_by_Gage_Skidmore.jpg",
            "description": "Es un cantante, compositor, músico, actor, abogado, político y activista panameño. Ha desarrollado gran parte de su carrera artística en la ciudad de Nueva York.",
            "birthDate": "1948-07-16T00:00:00.000Z"
        }
    ],
    "collectorAlbums": [
        {
            "id": 100,
            "price": 35,
            "status": "Active"
        }
    ]
}
