### ISSUE TITLE
HU02 Consultar la información detallada de un álbum

### ISSUE THREAD

**Issue by BaezRincon** [je-guerreroa1-uniandes/grupo-12-software-mobile#7]
Como usuario visitante quiero ver el detalle de un álbum para ampliar la información sobre él.

**Criterios de aceptación:**
-Muestra el nombre del álbum
-Muestra Descripción del álbum

**Sub tareas:**

- [ ] Modelar la respuestas con TDD - Mocks | 2h
- [ ] Integración servicio (Pruebas integración) | 2h
- [ ] Implementación UI | 1h 30m
- [ ] Integración UI + Servicio | 1h 30m
- [ ] Pruebas espresso | 1h
- [ ] Code review | 20m
- [ ] Merge conflicts(Opcional)

**Mockup(UI)**

![Image](https://user-images.githubusercontent.com/98714523/232351140-33f282ca-3193-4ebf-a0d7-d36648d0c763.png)

**Comment by Paolaafb22** [comment]
Como usuario visitante quiero ver el detalle de un álbum para ampliar la información sobre él.

Criterios de aceptación:
-Muestra el nombre del álbum
-Muestra Descripción del álbum

**Comment by BaezRincon** [comment]
<html>
<body>


Criterio | Comentario | 
-- | -- |
Completo | ✔️ La historia esta completa porque contiene lo necesario para cumplir con su objetivo. | 
Consistente | ✔️ La historia es consistente porque no presenta contradicciones ni inconsistencias |
Negociable | ✔️ La historia es negociable porque se presenta como necesaria | 
Valiosa | ✔️ La historia genera valor al cliente porque cubre un requerimiento necesario | 
Estimable | ✔️ La historia se puede estimar porque se puede estimar el esfuerzo para desarrollar la historia en una tecnología definida y conocida. | 
Pequeña | ✔️ La historia tiene un tamaño pequeño puede ser desarrollada en menos de 3 o 4 días para equipos de desarrollo de dos personas. | 
Comprobable | ✔️ La historia es comprobable porque la descripción de la historia y de los criterios de aceptación son suficientes para comprobar la correcta ejecución de la historia. |
