### ISSUE TITLE
HU01 Consultar catálogo de álbumes

### ISSUE THREAD

**Issue by BaezRincon** [je-guerreroa1-uniandes/grupo-12-software-mobile#8]
Como usuario quiero navegar el catálogo de los álbumes para escoger los que más me interesan.

*Criterio de aceptación:*

* Se visualizan albumes como listado
* Se visualiza imagen de cover de album
* Se visualiza el nombre del álbum

*Sub tareas:*

- [ ] Modelar la respuestas con TDD - Mocks | 2h
- [ ] Integración servicio (Pruebas integración) | 2h
- [ ] Implementación UI | 1h 30m
- [ ] Integración UI + Servicio | 1h 30m
- [ ] Pruebas espresso | 1h
- [ ] Code review | 20m
- [ ] Merge conflicts(Opcional)

*Mockup(UI)*

![Image](https://user-images.githubusercontent.com/98400664/232345727-1b9a260b-8a98-449b-9887-e44cf6d6f0ab.png)

**Comment by Paolaafb22** [comment]
<html>
<body>


Criterio | Comentario | 
-- | -- |
Completo | ✔️ La historia es objetiva en su formulación y se observa en el mockup los datos necesarios para su funcionamiento. | 
Consistente | ✔️ la historias de usuario es coherente con la necesidad planteada por el usuario. |
Negociable | ✔️ La historia es negociable dado que se presenta como necesaria para la aplicación | 
Valiosa | ✔️ La historia genera valor a la solución del problema mostrado por el usuario | 
Estimable | ✔️ La historia es estimable ya que esta detallada y delimitada la funcionalidad a crear.| 
Pequeña | ✔️ La historia está delimitada y muestra el objetivo de consultar catálogo de álbumes | 
Comprobable | ✔️ La historia se puede comprobar al seguir los pasos y los criterios de aceptación. |
